# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:android)

platform :android do
  desc "Build and sign the APK, then notify via Microsoft Teams"
  lane :build_apk do

    TEAMS_WEBHOOK_URL = ENV["TEAMS_WEBHOOK_URL"]
    COMMIT_HASH = `git rev-parse --short HEAD`.strip
    BRANCH_NAME = `git rev-parse --abbrev-ref HEAD`.strip
    GITHUB_URL = `git config --get remote.origin.url`.strip
    GITHUB_BRANCH_URL = "#{GITHUB_URL}/tree/#{BRANCH_NAME}"
    COMMIT_MESSAGE = `git log -1 --pretty=%B`.strip
    COMMIT_AUTHOR = `git log -1 --pretty=%an`.strip


    gradle(
      task: "clean"
    )

    gradle(
      task: "assembleRelease"
    )


    teams(
      teams_url: TEAMS_WEBHOOK_URL,
      title: "App Build Success 🚀",
      message: "Successfully build Android APK! 🚀 ",
      facts:[
        {
          "name"=>"Author",
          "value"=> COMMIT_AUTHOR
        },
        {
          "name"=>"Branch",
          "value"=> "<a href='#{GITHUB_BRANCH_URL}'>#{BRANCH_NAME}</a>"
        },
        {
          "name"=> "Commit",
          "value"=> "message: #{COMMIT_MESSAGE} - hash: #{COMMIT_HASH}"
        },
      ],
    )

  end
end



# You can define as many lanes as you want
platform :ios do
  desc "Build App for testing"
  lane :test do
    # run_tests(
    #   workspace: "AwesomeProject.xcworkspace",
    #   scheme: "AwesomeProject",

    # )

    build_app(
      workspace: "AwesomeProject.xcworkspace",
      scheme: "AwesomeProject",
      configuration: "Debug",
      export_method: "development",
      destination: "id=753EE107-5E89-4712-B1D2-445FBD5C973E",
    )
  end
end